name: Repo Sync

on:
  schedule:
    - cron: "*/1 * * * *" # every 15 minutes. set to whatever interval you like

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: repo-sync/github-sync@v2
        name: Sync repo to branch
        with:
          source_repo: "https://jhinning:${{ secrets.GITLAB_PAT }}@gitlab.com/jhinning/repo-sync3"
          source_branch: develop
          destination_branch: "repo-sync"
          github_token: ${{ secrets.PAT_TOKEN }}
      - uses: repo-sync/pull-request@v2
        name: Create pull request
        with:
          source_branch: "repo-sync"
          destination_branch: develop
          github_token: ${{ secrets.PAT_TOKEN }}
